name: Feature Docker

on:
  push:
    branches: [ "feature/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t testing . --tag myapp:test
