name: Feature Docker

on:
  push:
    branches: [ "feature/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      #run: docker build --target testing . --tag flask-mio
    - name: Run tests
      run: docker build --target test . --tag flask-mio
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: myapp:test
        platforms: linux/arm/v6
